### ISSUE TITLE
Add `block_hash` column to all the tables where `block_height` is presented

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#106]
@telezhnaya suggested a good improvement.

> I suggest adding block_hash column to all tables where block_height is presented (not in this PR though)

_Originally posted by @telezhnaya in https://github.com/near/read-rpc/pull/105#discussion_r1307664457_

This essentially requires to change the design of all the tables `state-indexer` maintains. In order to do that we need to have a good reason to recollect the data. 

So we decided to capture it in a separate issue and handle it once we meet (and we will for sure) a good reason to recollect the data.

**Comment by kobayurii** [comment]
Already added!
