### ISSUE TITLE
`query.function_call` ReadRPC returns error while NEAR RPC succeeds

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#115]
### The request

```
{
  "jsonrpc": "2.0",
  "id": "dontcare",
  "method": "query",
  "params": {
    "request_type": "call_function",
    "block_id": 100523214,
    "account_id": "ofpcore.near",
    "method_name": "get_stages_max_number",
    "args_base64": "eyJwcm9qZWN0X2lkIjogIjE2NjE5NDk3NjkxOTIifQ=="
  }
}
```

### ReadRPC response
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "Server error",
        "data": "Function call returned an error: wasm execution failed with error: CompilationError(PrepareError(Deserialization))",
        "name": "HANDLER_ERROR",
        "cause": {
            "info": {
                "block_hash": "74ENVfd6tHDCoKEfipcFWMDFyeJQR1EMX1J86oF2smtZ",
                "block_height": 100523214,
                "vm_error": "wasm execution failed with error: CompilationError(PrepareError(Deserialization))"
            },
            "name": "CONTRACT_EXECUTION_ERROR"
        }
    },
    "id": "dontcare"
}
```

### NEAR RPC response
```
{
    "jsonrpc": "2.0",
    "result": {
        "block_hash": "74ENVfd6tHDCoKEfipcFWMDFyeJQR1EMX1J86oF2smtZ",
        "block_height": 100523214,
        "logs": [],
        "result": [
            34,
            51,
            50,
            34
        ]
    },
    "id": "dontcare"
}
```

We might need help from the contract runtime team. Perhaps there are some corner cases in the way we run the contract that lead to 

```
"wasm execution failed with error: CompilationError(PrepareError(Deserialization))"
```

**Comment by miraclx** [comment]
Let's update the rust base images in docker to `>0.70` and see what happens then. I suspect the contract deployed on `ofpcore.near` might've been built with a version of rust that includes instructions from the signed extensions proposal.

Context: https://github.com/near/nearcore/pull/9140

**Comment by kobayurii** [comment]
> Let's update the rust base images in docker to `>0.70` and see what happens then. I suspect the contract deployed on `ofpcore.near` might've been built with a version of rust that includes instructions from the signed extensions proposal.
> 
> Context: [near/nearcore#9140](https://github.com/near/nearcore/pull/9140)

Thank you for your reply. I've already done some research on this subject. We need to wait for the near 0.18.0 release, which includes the nearcore 1.35 update. This should fix this error.

**Comment by khorolets** [comment]
@kobayurii `0.18.0` of the crates we're waiting for will not happen immediately. I recall we stopped using the git-based versions because we had a conflict in `near-jsonrpc-client` and `near-jsonrpc-primitives`. We can try to use the newer versions of the crates we need from git directly and patch the versions of the conflicting ones using the `[patch.crates-io]` directive in `Cargo.toml`

ref: https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html

**Comment by kobayurii** [comment]
https://github.com/near/read-rpc/pull/139
