### ISSUE TITLE
Potential partition growth for some tables in the ScyllaDB

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#118]
@telezhnaya and I were reviewing the ReadRPC project and its requirements. We have discussed the high availability and horizontal scale in particular. That led us to a talk about the ScyllaDB, our database's design, and how it can be scaled horizontally.

We’ve noticed that tables:

state_changes_contract

state_changes_account

maybe some other

Those with the partition key account_id can grow in size in some specific circumstances. state_changes_contract can grow if some accounts constantly deploy a new code every block. It eventually will lead to the growth of that account partition. 

However, the described issue has a low possibility of worrying about it. So we’ve decided to create an issue noting the potential problem for the future selves.

**Comment by kobayurii** [comment]
Since we migrated to Postgres this issue is already not actual. https://github.com/near/read-rpc/pull/282
