### ISSUE TITLE
CORS headers missing

### ISSUE THREAD

**Issue by Tarnadas** [near/read-rpc#121]
Hey,

I tried using `https://beta.rpc.mainnet.near.org` from within a browser and I noticed that no CORS headers are set, which results in this error:

![image](https://github.com/near/read-rpc/assets/5855071/a03327a2-e946-4ca4-a80d-d7f8f2750aa9)

Using the regular RPC server works, because CORS headers are present.

**Comment by andrei-near** [comment]
Hi @Tarnadas,

Thank you for bringing this up.
It should be fixed now. Please check on your end and let us know.

Cheers
