### ISSUE TITLE
Slowing down of some contracts due to state provision in contract runtime

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#150]
Hello everyone! I want to highlight an issue we've recently encountered.

The current method of provisioning state to the contract runtime is causing a slowdown in executing certain contracts. For example, the `poolv1` contract's `get_accounts` view method takes about **200ms** to execute on NEAR RPC, but it **exceeds 17 seconds** on ReadRPC.

After looking it over, we found out the cause. Rather than retrieving the complete state from the database (ScyllaDB) and presenting it to the contract runtime, we enable the contract runtime to query the state from the database directly via host functions. This approach is efficient for contracts with few state queries. However, for contracts that execute numerous queries under the assumption that the state resides in RocksDB (as in the case with NEAR RPC), this leads to significant slowdowns, with most of the time spent in state retrieval.

To address this, we considered caching the entire state in RAM. The primary concern is managing a potentially large state without overloading the RAM. Our solution involves two parallel state provisioning methods: the current approach and a new "RAM-first" strategy. We'd like to introduce a timeout to try state retrieval within a set period. If the state isn't retrieved in this timeframe, indicating a large size, we will revert to provisioning host functions for database interaction, as is currently done. However, this might negatively impact scenarios where direct database access is efficient, as they would be forced to wait for complete state retrieval (or until the timeout, in the case of a large state). We can only determine the contract size during the retrieval process, which complicates the decision on which approach to apply.

Our goal is to improve performance in problematic cases without adversely affecting those that currently function well.

I've attempted to illustrate this in the accompanying diagrams. The top diagram represents the existing process, while the bottom diagram proposes the new approach. However, we can't implement this solution as-is without impacting the performance of contracts that currently run efficiently.

![ReadRPC call_function](https://github.com/near/read-rpc/assets/3235740/83efd201-b7ed-4acd-9328-ed49021e1b01)

We're considering implementing this solution under a feature flag as an alternative. This will allow node operators to deploy a ReadRPC node with this feature enabled if they believe it will benefit their users.

I eagerly await feedback and suggestions from fellow developers and node operators.

**Comment by frol** [comment]
Not so many contracts use more than 1 MB of storage, so you may at least start loading the whole state for the contracts under 1 MB of storage. Ideally, it should be implemented as a caching layer abstraction, but cache invalidation might be challenging, so you may want to skip it for now.
