### ISSUE TITLE
(rpc-server): Query_view_account - Error messages mismatch 

### ISSUE THREAD

**Issue by kobayurii** [near/read-rpc#156]
The errors are a little different.

 rpc-server
```
{
     "info": {
          "block_hash": {block_hash}, 
          "block_height": {block_height}, 
          "requested_account_id": {account_id}
     }, 
     "name": "UNKNOWN_ACCOUNT"
}
```

Near RPC
```
{"info": {"requested_shard_id": {shard_id}}, "name": "UNAVAILABLE_SHARD"}}.
 ```

I'm not sure we can set up an exact error match here.

**Comment by frolvanya** [comment]
Has this issue been resolved already?

![image](https://github.com/near/read-rpc/assets/59515280/d0e1f6b3-1612-4a38-9993-6c96f87e3843)
