### ISSUE TITLE
Total requests metrics

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#183]
We need to calculate the number of requests the ReadRPC node receives and how many are proxied to the NEAR RPC (unsupported methods, write methods, etc.)

We already have separate method counter metrics for all of the supported methods. By adding a total counter, we would be able to calculate the percentage of requests broken down by methods, and we would be able to get a number of those proxied.

This counter needs to be incremented before the logic could proxy the request.

**Comment by kobayurii** [comment]
https://github.com/near/read-rpc/pull/184
