### ISSUE TITLE
Redesign data collection and storage for `query.view_access_key_list` RPC method

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#187]
## Problem Description

The original approach attempted to store snapshots of all access keys for each account at each block height, updated during transactions. This method, however, was not scalable for accounts or access keys with high transaction volumes. Each transaction update—triggered by a `nonce` update when a key was used — resulted in a new record combining `account_id`, `block_id`, and a dump of all access keys (as structs). This process created enormous and hot partitions in the database, leading to significant scalability and performance issues. We decided to hide the logic and implementation of the `query.access_key_list` method behind a `feature` and disable it until we find a better solution.

## Task Objective:

Design a fundamentally different approach for collecting and storing data to support the query efficiently. The new design must address the critical problems of data duplication, partition size, and the inability to parallelize operations. This redesign aims not only to enhance performance but also to ensure scalability and maintainability of the system.

## Expected Outcomes:

* A scalable, efficient schema and logic for the account_access_keys data collection and storage.
* Improved performance and reliability of the `state-indexer`.
* Detailed documentation of the new approach, including schemas, logic flow, and potential impacts on existing systems.

## Considerations:

* Explore partitioning strategies that prevent large partition sizes.
* Evaluate the possibility of parallelizing data operations.
* Ensure the new design does not adversely affect the current system's functionality.

**Comment by kobayurii** [comment]
Due to the migration to Postgres, this problem is solved here https://github.com/near/read-rpc/pull/282
