### ISSUE TITLE
View calls are either too slow or return HTTP/502 (Bad Gateway) error

### ISSUE THREAD

**Issue by frol** [near/read-rpc#193]
```
near contract call-function as-read-only nodeasy.poolv1.near get_accounts json-args '{"from_index": 500, "limit": 500}' network-config mainnet-beta now
```

It works fast on regular RPC, but beta RPC takes 30 seconds or more, and sometimes I get HTTP/502 Bad Gateway response.

**Comment by kobayurii** [comment]
Hi! Thank you! It looks like we already have a n issue related to this problem. https://github.com/near/read-rpc/issues/150.
