### ISSUE TITLE
`tx` request returns "Invalid params" to a totally valid request

### ISSUE THREAD

**Issue by frol** [near/read-rpc#212]
<img width="701" alt="image" src="https://github.com/near/read-rpc/assets/304265/1499baea-4522-40a2-a9ec-7885b5596280">

```sh
curl --location 'https://beta.rpc.mainnet.near.org' \
          --header 'Content-Type: application/json' \
          --data '{
        "jsonrpc": "2.0",
        "id": "dontcare",
        "method": "tx",
        "params": ["FgCth6YNtjHaZPK7oKmD8rtCLNCpcr99qWUi5jHr5CkZ", "near"]
      }'
```

Exactly the same request to regular RPC works fine (you just need to take a recent transaction hash to get the response)

**Comment by kobayurii** [comment]
Thx! It will be fixed coming soon! 
https://github.com/near/read-rpc/pull/213
