### ISSUE TITLE
Improve the proxy to be smarter

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#231]
We've got a report about an interesting issue we missed or postponed.

## The problem

Using the https://github.com/near/near-cli-rs to get the account summary for some old block

```
near account view-account-summary khorolets.near network-config mainnet at-block-height 111809623
```

Results with the error:

```
Error:
   0: Failed to fetch ViewAccessKeyList for khorolets.near
   1: handler error: [The data for block #111809623 is garbage collected on this node, use an archival node to fetch historical data]
```

Error 0 leads us to believe it is related to the method `query.view_access_key_list`, which is not supported until #187 is done.
Error 1 tells us we hit a regular node that garbage-collected the requested block.

## Solution

While we don't natively support the `query.view_access_key_list` method, we must empower our proxy with some logic. If I recall correctly, we have this smart proxy for some of the methods.

We need the code to react to the requested block height. If it is not within the last four (4) epochs, we need to proxy it to the archival node; otherwise, to the regular. Thus, we keep the archival node out of redundant requests but hit it when needed.

## Additionally

I encourage us to extend the "fix" of this issue to other methods where:
* We proxy them
* Method involves `block_reference`
* Smart proxy is not implemented there yet

**Comment by kobayurii** [comment]
https://github.com/near/read-rpc/pull/233
