### ISSUE TITLE
(rpc-server): EXPERIMENTAL_changes - Results mismatch

### ISSUE THREAD

**Issue by kobayurii** [near/read-rpc#262]
Request example:
```
{
    "jsonrpc": "2.0",
        "id": "dontcare",
        "method": "EXPERIMENTAL_changes",
        "params": {
          "changes_type": "data_changes",
          "account_ids": ["a.mitte-orderbook.near"],
          "key_prefix_base64": "",
          "block_id": "4DvesCRurdxtu3kPy9wTeGgzjvD2timR8PF6rzeidtQs"
        }
}
```
Read_RPC result:
![image](https://github.com/near/read-rpc/assets/20987138/2ec90b98-ef6e-45b5-8e22-d09d95599844)

[rpc.mainnet.near.org](http://rpc.mainnet.near.org/) result:
![image](https://github.com/near/read-rpc/assets/20987138/d17a92e3-2f3a-4b17-890a-a42c99fe86b0)

**Comment by frolvanya** [comment]
Is there a possibility that it was an issue on mainnet rpc's side? Because right now the request to rpc.mainnet.near.org shows the same result as read rpc on you screenshot

<img width="1156" alt="image" src="https://github.com/user-attachments/assets/10ea51a4-4faa-4175-abe1-de012bf1b29c">
