### ISSUE TITLE
(rpc-server): Make Redis dependency optional

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#279]
Continuation of #274 

First of all, we need to decide how to proceed with having Redis as a mandatory dependency and whether the `rpc-server` can work without it even with limited capabilities.

From what I can gather, we have all the logic to fallback into alternative way of getting the data if the Redis is not available. While it is not something we want in production environment, it is totally acceptable in the development.

I need to hear if @kobayurii has second thoughts about it and we can proceed with this issue.

**Comment by kobayurii** [comment]
Redis is not a critical dependency and is only intended to handle optimistic blocks. We can check and ignore the connection to redis at the initialization stage of the service if it cannot be established.
