### ISSUE TITLE
Support new method EXPERIMENTAL_congestion_level

### ISSUE THREAD

**Issue by telezhnaya** [near/read-rpc#375]
### What talent are you looking for?

None

### What you need to be done?

see nearcore implementation for the details

### Currency

USDC.e

### KYC

- [ ] Use KYC Verification

**Comment by kobayurii** [comment]
Thank you! Support new methods will be added soon.

**Comment by kobayurii** [comment]
This will be included in the 0.3.2 release https://github.com/near/read-rpc/pull/373
