### ISSUE TITLE
Split error metrics to disambiguate the reason 

### ISSUE THREAD

**Issue by khorolets** [near/read-rpc#97]
@kobayurii @telezhnaya 
I've talked to @gmilescu, who suggested we split the errors in the counters. Something like:
- `block_error_proxies_counter_0` - RR success, AR success - data mismatch
- `block_error_proxies_counter_1` - RR success, AR error
- `block_error_proxies_counter_3` - RR error, AR success

This is similar to what @kobayurii did in #93 PR for separating logs. What do you think?

_Originally posted by @khorolets in https://github.com/near/read-rpc/issues/93#issuecomment-1662370835_

**Comment by telezhnaya** [comment]
I agree, but we should also add a fourth option
block_error_proxies_counter_4 - RR error, AR error, data mismatch
